### ISSUE TITLE
Dockerfile and docker-compose for easy deployment

### ISSUE THREAD

**Issue by btorresgil** [privacybot-berkeley/privacybot#2]
Containerizing this app would help reduce setup effort and eliminate the need for python, pip, node, etc.

I can try to send you a pull request, if you like. Just let me know, does the app store anything locally where it would need a persistent volume?

Thanks!

**Comment by privacybot-berkeley** [comment]
Hello Brian,

Thanks so much for your message. We are working on making an installer for
PrivacyBot hoping it would eliminate the need to install python pip, node
etc.

We'll definitely reach out to you if we decide Docker would be a better
option.

Best Regards,
Archana.

**Comment by j94c** [comment]
^ ditto this.
