### ISSUE TITLE
Committed secrets file

### ISSUE THREAD

**Issue by zackdotcomputer** [privacybot-berkeley/privacybot#4]
https://github.com/privacybot-berkeley/privacybot/blob/master/app/client_secret.json

Looks like a secret file has been committed. This is probably unintentional and you will likely want to rm and ignore this file and then rotate this secret value for your own purposes.

**Comment by j94c** [comment]
so the name "client_secret" is a bit of a misnomer as far as we can tell. Basically this file has to do with the project's verification with Google API to use Oauth + gmail scopes. We followed the specific instructions for doing this with a desktop application and it needs to be there for the sign in with gmail to work. You are welcome to create a new google api cred and use it instead.
